### PR TITLE
Update to AsyncKeyedLock 6.2.1

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This version now provides an alternate technique called striped locking. With this PR, nothing changes in the way things are done, but if you would like to check out the advantages and disadvantages of the new mechanism, please read up on it at https://github.com/MarkCiliaVincenti/AsyncKeyedLock/wiki

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@Y0lan :)

**Comment by Y0lan** [comment]
> @Y0lan :)

Why are you opening PR on this project?

**Comment by MarkCiliaVincenti** [comment]
> > @Y0lan :)
> 
> Why are you opening PR on this project?

Saving you time and effort to update to the latest version :)

**Comment by Y0lan** [comment]
> > > @Y0lan :)
> > 
> > Why are you opening PR on this project?
> 
> Saving you time and effort to update to the latest version :)

This project is abandoned

**Comment by MarkCiliaVincenti** [comment]
> This project is abandoned

I see, I did not realise this. Please either merge or close this PR then and I will not create more PRs.

**Pull request closed without merging**
